# Generated by Django 6.0.1 on 2026-01-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LI_userID', models.CharField(max_length=100)),
                ('LI_userName', models.CharField(max_length=100)),
                ('LI_passWord', models.CharField(max_length=100)),
            ],
        ),
    ]
