# Generated by Django 6.0.1 on 2026-01-29 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0002_tbladmdepartment_tbl_admuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_admuser',
            name='credentials',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='userLogin.usercredentials'),
        ),
    ]
