# Generated by Django 6.0.1 on 2026-02-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0003_tbl_admuser_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='isDeploy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='isUser',
            field=models.BooleanField(default=True),
        ),
    ]
