# Generated by Django 6.0.1 on 2026-02-04 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0004_usercredentials_isadmin_usercredentials_isdeploy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredentials',
            name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='usercredentials',
            name='isDeploy',
        ),
        migrations.RemoveField(
            model_name='usercredentials',
            name='isUser',
        ),
    ]
