# Generated by Django 6.0.1 on 2026-02-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0005_remove_usercredentials_isadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='LI_passWord',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='LI_userName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
