# Generated by Django 6.0.1 on 2026-02-04 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0006_alter_usercredentials_li_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_admuser',
            name='credentials',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userLogin.usercredentials'),
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='LI_userName',
            field=models.CharField(max_length=100),
        ),
    ]
