# Generated by Django 6.0.1 on 2026-02-05 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userLogin', '0007_alter_tbl_admuser_credentials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketCode', models.CharField(max_length=200, unique=True)),
                ('ticketSeverity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('ticketTitle', models.CharField(max_length=200)),
                ('ticketBody', models.TextField()),
                ('ticketStatus', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='OPEN', max_length=50)),
                ('ticketCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ticketUpdatedAt', models.DateTimeField(auto_now=True)),
                ('ticketAssignedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='userLogin.tbl_admuser')),
                ('ticketAuthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to='userLogin.tbl_admuser')),
                ('ticketDeployer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_Deployed', to='userLogin.tbl_admuser')),
            ],
        ),
    ]
